.travis.yml

Seems like it would be nice to test under the latest stable Go version.
Travis CI also has some [nice new infrastructure](http://docs.travis-ci.com/user/migrating-from-legacy/) that starts builds almost instantaneously (within 10 seconds) and run faster (in many cases).

Use Go 1.5 on Travis-CI

---

main.go

9db5229 changed this, but the usage message wasn't updated. I've taken a stab at that, although my wording is clunky.

Correct usage explanation of where code is written

---

arguments/parser.go
arguments/parser_test.go

https://github.com/maxbrunsfeld/counterfeiter/commit/88a92016cda4bacc1da3651e38f1feeb2e38bde2 is breaking our tests as we allow underscores in package names.

adding underscore to the range of valid package names

---

.gitignore
astutil/mutator.go
fixtures/dot_imports.go
fixtures/dup_packages/a/a.go
fixtures/dup_packages/a/v1/a.go
fixtures/dup_packages/alias.go
fixtures/dup_packages/b/v1/b.go
fixtures/dup_packages/dupA.go
fixtures/dup_packages/dupAB.go
fixtures/dup_packages/dupB.go
fixtures/dup_packages/dup_packagenames.go
fixtures/dup_packages/v1/multi_import.go
generator/generator.go
locator/locate_function.go
locator/locate_interface.go
locator/locator.go
locator/locator_test.go
model/model.go

- track imports based on their alias
- test duplicate package names
- test dot imports are not affected

Handle duplicate package names properly

---

README.md
arguments/parser.go
arguments/parser_test.go
integration/integration_test.go
locator/locate_interface.go
locator/locator.go
main.go

Replace interactive single argument behavior to specify which interface
to fake out with a new behavior that let's the user generate fakes for
arguments they do not own. This works by specifying a fully qualified
interface path (eg "counterfeiter net/http.CloseNotifier"). The fake is
generated in the current fakes directory.
[Issue #46]

Fake out foreign interfaces

---

fixtures/expected_output/fake_something_factory.example
fixtures/packagegen/packagegenfakes/fake_os.go
generator/generator.go
generator/generator_test.go

stubbedMethodImplementation generates a superfluous block around possible final return statement. This triggers a warning in some Go linters.

Remove superfluous else block

---

.travis.yml
fixtures/vendored/bar/bar.go
fixtures/vendored/bar/vendor/apackage/interface.go
fixtures/vendored/baz/baz.go
fixtures/vendored/foo.go
fixtures/vendored/vendor/apackage/interface.go
locator/locate_interface.go
locator/locator.go
locator/locator_test.go
scripts/make_fakes.sh

This implements basic support for finding interfaces and types from vendored code and may resolve #50. If the general approach is reasonable, I'm happy to rework as necessary.
Regardless, it works for my typical use cases of composing interfaces that are sourced from vendored code and using types from vendored code on my interfaces.

Basic support for vendored code

---

.travis.yml
scripts/deps.sh

Set go_import path to github.com/maxbrunsfeld/counterfeiter
to make forks build properly.
This should fix build failures in pull requests like this: https://github.com/maxbrunsfeld/counterfeiter/pull/69#issuecomment-303829068

Don't go get subpackages of counterfeiter on travis

---

README.md

There is a broken link in the README.
❌ counterfeiter_test.go -> ✅ generated_fakes_test.go

Fix test examples url

---

generator/fake.go
generator/generator_internals_test.go
generator/import.go
generator/interface_loader.go
generator/loader.go
main.go

I have been a user of this project for a while and I just started taking a look at the code. I noticed a few unused things, and functions that could be simplified a bit.
Each commit is a distinct small cleanup with a commit message that should hopefully explain it. If you prefer I would be happy to drop one or more of the commits, or squash the commits to a single commit.

Small code cleanup

---

generator/fake.go
generator/function_loader.go
generator/function_template.go
generator/generator_internals_test.go
generator/interface_loader.go
generator/interface_template.go
generator/package_template.go

While reading over the code I noticed a couple fields on the `Method` struct that I found particular hard to understand. After reading over the code I realized these fields held copies of values from `Fake`.  They appear to exist solely to render values into the template, but do not feel like natural properties of a `Method` type.
I noticed that at the bottom of https://golang.org/pkg/text/template/#hdr-Variables it says `$` is always set to the initial value of `.`. Using `$` I was able to remove these copied values and use the original value from the `Fake`. 
Fewer fields, especially fields that contain values which are copies of other values, should make the code easier to understand.

Remove duplicate value fields

---

arguments/files.go
arguments/parser.go
arguments/parser_test.go
arguments/parser_windows_test.go
main.go

Full description in the commit message.
One of the stated goals in the readme of this project is to keep `main` small. I noticed some duplicate code and unused function in main that could be cleaned up.

Shrink main package

---

generator/function_template.go
generator/import.go
generator/import_test.go
generator/interface_template.go
generator/package_template.go
integration/testdata/expected_fake_somethingfactory.txt
integration/testdata/expected_fake_writecloser.txt

Branched from #109
Format the import line in `Import.String()` so that the template only needs to print the import and unnecessary aliases (where the alias is identical to the package path base) will not be added.

Only add import aliases to fake package when necessary

---

fixtures/inline_struct_params.go
fixtures/inlinestructs/interface.go
generator/loader.go

I recently encountered some odd behaviour when generating mocks for interfaces making use of anonymous / inline structs (as mentioned in this issue https://github.com/maxbrunsfeld/counterfeiter/issues/128).
This PR aims to address that issue.
- Updated the generator to recurse through struct fields and add imports for their types
- Added a text fixture for this kind of interface

Imports for inline structs

---

command/runner_test.go
generator/generator_internals_test.go
go.mod

Fix test failure on go 1.13

---

command/runner_test.go
go.mod

Go 1.13 automatically adds `go 1.13` if it's missing,
which is wrong and breaks the test script too because it fails
if there are uncommitted changes.
Fixes #131

Add go 1.11 directive to go.mod

---

command/runner_test.go

A new test was added in e8250336a23688f78f496c7831ff8d7aa2636535
with a counterfeiter:generate comment, so the number of invocations
has increased by one.

Fix test failure

---

generator/loader.go
integration/roundtrip_test.go

x/tools/go/packages does not search inside vendor.
Work around by using build.Import first to find the package in vendor.
See https://github.com/golang/go/issues/30289
There aren't any tests with a vendor directory, so I only tested this manually on a project that uses it and wants to generate a fake for a vendored package. I can try to write some test fixtures if you'd like.
Fixes #75

Fix importing of vendored packages

---

fixtures/aliased_package/aliased_packagefakes/fake_in_aliased_package.go
fixtures/another_package/another_packagefakes/fake_another_interface.go
fixtures/fixturesfakes/fake_aliased_interface.go
fixtures/fixturesfakes/fake_dot_imports.go
fixtures/fixturesfakes/fake_embeds_interfaces.go
fixtures/fixturesfakes/fake_first_interface.go
fixtures/fixturesfakes/fake_has_imports.go
fixtures/fixturesfakes/fake_has_other_types.go
fixtures/fixturesfakes/fake_has_var_args.go
fixtures/fixturesfakes/fake_has_var_args_with_local_types.go
fixtures/fixturesfakes/fake_imports_go_hyphen_package.go
fixtures/fixturesfakes/fake_inline_struct_params.go
fixtures/fixturesfakes/fake_reuses_arg_types.go
fixtures/fixturesfakes/fake_second_interface.go
fixtures/fixturesfakes/fake_something.go
fixtures/fixturesfakes/fake_something_else.go
fixtures/fixturesfakes/fake_something_factory.go
fixtures/fixturesfakes/fake_something_with_foreign_interface.go
fixtures/fixturesfakes/fake_unexported_func.go
fixtures/fixturesfakes/fake_unexported_interface.go
fixtures/sql/sqlfakes/fake_db.go
fixtures/sync/syncfakes/fake_sync_something.go
generator/function_template.go
generator/interface_template.go

Prevent a data race from occurring by deferring `mutex.Unlock`.
- Fixes #141 
- Fixes #149

 Defer unlocks in fake function and interface calls

---

arguments/parser.go
arguments/parser_windows_test.go
main.go

Hi there!
First of all, thanks for all your efforts in building this great tool!
I'm submitting a PR to add a `-q` command line flag to hide the status logs it emits when generating fakes. For example,
```
Writing `FakeFoo` to `path/to/fake_foo.go`... Done
```
This would reduce the chatter in our build logs and allow us to more easily identify problematic lines.

Add -q flag to suppress status output

---

command/runner.go
command/runner_internals_test.go
command/runner_test.go

Fixes #166.
@joefitzgerald According to the usage message from counterfeiter, the `-generate` flag is supposed to cause it to evaluate all and only the `//counterfeiter:generate` directives in the current package.
> 	-generate
> 		Identify all //counterfeiter:generate directives in .go file in the
> 		current working directory and generate fakes for them. You can pass
> 		arguments as usual.
> 
> 		NOTE: This is not the same as //go:generate directives
> 		(used with the 'go generate' command), but it can be combined with
> 		go generate by adding the following to a .go file:
> 
> 		# runs counterfeiter in generate mode
> 		//go:generate go run github.com/maxbrunsfeld/counterfeiter/v6 -generate
Consequently, the existing behavior of trying to also include `//go:generate counterfeiter` …

separate go:generate logic from counterfeiter:generate logic
